/**
 * Shared English UI phrases used across PlateGuard screens.
 * Keep English as the source of truth in logic; pass these through
 * `usePhrases` and call `tp("…")` only when rendering.
 */

export const COMMON_PHRASES = [
  "Home",
  "Scan",
  "History",
  "Card",
  "Profile",
  "Back to Home",
  "Try again",
  "Go home",
  "Cancel",
  "Continue",
  "Save",
  "Delete",
  "Close",
  "Loading…",
  "Please wait…",
  "Unnamed profile",
  "Use caution",
  "Avoid",
  "Risky",
  "Mostly safe",
  "Safe",
  "Do not eat",
  "Scan history",
  "No profile yet",
  "Create a profile",
  "Name",
  "Select",
  "Optional",
] as const;

export const SCAN_PHRASES = [
  ...COMMON_PHRASES,
  "Starting scan…",
  "Preparing label…",
  "Checking product barcode…",
  "Looking up product details…",
  "Analyzing label with AI…",
  "Building your result…",
  "Saving to history…",
  "Scan complete",
  "Preparing product information…",
  "Analyzing with AI…",
  "Preparing file…",
  "Food label",
  "Medicine label",
  "Medicine",
  "Captured label",
  "Pasted label text",
  "Upload a photo or PDF",
  "Take photo",
  "Paste label text",
  "Look up barcode",
  "Scan barcode",
  "Scan failed",
  "Barcode lookup failed — check your connection and try again.",
  "Every scan is judged against it, so we need it before your first scan.",
  "Name for the new profile (e.g. a family member)",
  "Create profile",
  "Switch profile",
  "Active profile",
  "Scan again",
  "View history",
  "Recommendation",
  "Flagged ingredients",
  "Nutrition highlights",
  "Product",
  "Why this rating",
  "Label evidence",
  "Active ingredients",
  "This may take about 15–30 seconds",
  "Scanning for",
  "Opening barcode camera…",
  "Camera access was blocked.",
  "Requesting camera permission…",
  "Live camera isn't supported here",
  "Scan progress",
  "Close barcode camera",
  "Close camera",
  "Open gallery",
  "Capture photo",
  "Open phone camera",
  "AI capacity",
  "Paste ingredients",
  "Run scan",
  "Retake",
  "New scan",
,
  "Scan another label",
  "Scan a label",
  "Analyze product",
  "Analyzing…",
  "Non-food item",
  "Point the barcode inside the box — scanning automatically",
  "Close barcode camera",
  "Close camera",
  "Open gallery",
  "Capture photo",
  "Open phone camera",
  "Ingredients: oats, sugar, sodium…",
  "e.g. Harvest Oat Granola",
  "e.g. 8908010046488",
  "Camera access was blocked",
  "Scan history"
] as const;

export const PROFILE_PHRASES = [
  ...COMMON_PHRASES,
  "Health profile",
  "About you",
  "Allergies",
  "Health conditions",
  "Sensitivities",
  "Lifestyle & medications",
  "Who is this for?",
  "Save profile",
  "Select allergens",
  "Search allergens…",
  "Select severity",
  "Not applicable",
  "Select if relevant",
  "Select type",
  "Select treatment",
  "Select status",
  "Select any that apply",
  "Remove profile photo",
  "Profile photo updated.",
  "Could not upload the photo.",
  "Please choose an image file.",
  "Please choose an image smaller than 8 MB.",
  "Could not process the image.",
  "Name for the new profile (e.g. a family member)",
  "Your health profile",
  "Set your complete profile once; every scan is judged against all of it together.",
  "Profile photo",
  "Optional • helps identify profiles",
  "Name (optional)",
  "Age group",
  "Biological sex",
  "Pregnancy / breastfeeding status",
  "Weight (kg, optional)",
  "Activity level (optional)",
  "Height (optional)",
  "Select every allergen that applies",
  "How severe is the reaction, typically?",
  "Gluten status (optional)",
  "Diabetes detail",
  "Type",
  "Treatment",
  "Kidney detail",
  "Chemical / additive sensitivities (optional)",
  "Digestive symptom pattern (optional)",
  "Dietary / religious pattern (optional)",
  "Current medications (optional)",
  "Anything else to watch for?",
  "Specific sensitivities",
  "Lifestyle, medications & anything else",
  "Age, sex, and body baseline change what's actually risky in a food — not just what's flagged.",
  "Treated as life-critical — any direct ingredient or hidden derivative triggers the highest-risk rating.",
  "Select everything that applies, not just the most urgent one — conditions are weighed together, since combinations can even reverse each other's dietary advice.",
  "Not allergies, but things that still change what's comfortable to eat — only flagged if you select them.",
  "Dietary and religious patterns add a separate layer of checks; medications matter only for well-established food-drug interactions.",
,
  "Remove profile photo",
  "e.g. Maya",
  "Select",
  "Select if relevant",
  "e.g. 62",
  "e.g. 165",
  "e.g. 5",
  "Select allergens",
  "Select severity",
  "Not applicable",
  "Select type",
  "Select treatment",
  "Select status",
  "Select any that apply",
  "e.g. warfarin, lisinopril",
  "e.g. also avoid red food dye; sodium under 140mg per serving",
  "Every field feeds one rating — nothing here is judged in isolation."
] as const;

export const HISTORY_PHRASES = [
  ...COMMON_PHRASES,
  "Scan history",
  "Clear all scan history on this device?",
  "Unreadable label",
  "Scan details",
  "Delete scan",
  "Scanned label",
  "Active ingredients",
  "Label evidence",
  "Nutrition & ingredient highlights",
  "Flagged ingredients",
  "Recommendation",
  "No scans yet",
  "Your recent food and medicine label verdicts, with full AI scan details.",
  "Clear history",
  "Scan a label",
  "Swipe to see each product",
  "AI verdict",
  "What the AI found",
  "What it is",
  "AI reasons",
  "Purpose",
  "Select to compare",
,
  "Flagged",
  "Profile impact",
  "Saved before detailed AI results were enabled — only the summary verdict is available.",
  "How it affected the profile"
] as const;

export const CARD_PHRASES = [
  ...COMMON_PHRASES,
  "Emergency Card",
  "Emergency Health Card",
  "Select a profile",
  "Copy as text",
  "CONDITIONS:",
  "CURRENT MEDICATIONS:",
  "DIETARY / RELIGIOUS PATTERN:",
  "Generated by PlateGuard AI — not a substitute for medical advice.",
  "Allergies",
  "Print / Share",
  "Create a profile",
  "Name",
  "Copied!",
,
  "No profile yet",
  "Emergency Card"
] as const;

export const LOGIN_PHRASES = [
  ...COMMON_PHRASES,
  "Welcome back",
  "Create your account",
  "At least 6 characters",
  "Hide password",
  "Show password",
  "New here? Create an account",
  "Already have an account? Log in",
  "Log in",
  "Sign up",
  "Email",
  "Password",
  "Continue with Google",
  "Unable to continue with Google.",
  "Account created. Check your email to confirm, then log in.",
  "Unable to continue.",
,
  "Your profiles and scan history are saved securely to your account.",
  "Email address",
  "you@example.com",
  "Continue with Google"
] as const;

export const SAFETY_PHRASES = [
  ...COMMON_PHRASES,
  "Safety Center",
  "How to use a scan safely",
  "A scan is a safety aid, not a guarantee",
  "Always check the physical package when the result is uncertain, the label is unreadable, or the product does not look like the identified item.",
  "Know the 1–5 rating",
  "5/5 — Safe: no relevant concern was found from the available evidence.",
  "4/5 — Likely safe: low concern, but review the details if the product matters for a strict diet.",
  "3/5 — Use caution: something is uncertain or needs verification.",
  "2/5 — High concern: avoid unless you can verify the issue is not relevant.",
  "1/5 — Unsafe: do not consume or use for eating.",
  "Barcode vs. label",
  "A barcode can identify a catalogued product even when you do not have the ingredients text.",
  "If the barcode identifies a different product from what you are holding, stop and scan the physical label instead.",
  "If the result looks wrong",
  "Do not rely on the rating yet.",
  "Check the product name, ingredients, allergen statement, and warnings on the package.",
  "Rescan a clearer image or paste the label text manually.",
  "For a serious allergy or medical restriction, follow the advice of your clinician or pharmacist.",
  "Non-food products",
  "Cosmetics, perfume, body lotion, cleaning products, medicines, and other non-food items are not food. They should never receive a “safe to eat” interpretation.",
  "If PlateGuard identifies an item as non-food, treat it as not edible regardless of its ingredient safety rating.",
  "Need another check?",
  "Open your scan history to review the complete AI explanation from a previous scan, or start a new scan for clearer evidence.",
  "Scan a product",
  "scan history",
] as const;

export const HOME_PHRASES = [
  ...COMMON_PHRASES,
  "The taste of certainty",
  "Reading every label",
  "Protecting every bite",
  "Smarter scans. Safer bites. Every label decoded in plain English, for every aisle in the store.",
  "Start scanning",
  "Set your profile",
  "Scroll",
  "Typical time to a verdict",
  "Allergens tracked by default",
  "Health conditions supported",
  "Ingredients left to guesswork",
  "Connecting a photo, an ingredient list, and your medical profile through one careful check — making every trip down the snack aisle faster, calmer, and genuinely informed.",
  "How it works",
  "User guide",
  "What we scan",
  "Verdicts",
  "Safety",
  "Clear verdict",
  "Green, caution, or red — typically ready in 15–30 seconds",
  "How a scan becomes a verdict",
  "Built for trust",
  "Every ingredient, read in place",
  "Matched against your profile",
  "One plain answer, one reason",
  "Label scan",
  "Cross-check",
  "Real scans",
  "Languages supported",
  "Auto-detected on scan",
  "Checking your account…",
  "Every aisle, covered.",
  "Account",
  "When in doubt, don't eat it.",
  "Toggle menu",
  "Scroll to learn more",
  "Play video",
  "Playback speed",
  "Scroll left",
  "Scroll right",
  "Allergy match",
  "Condition check",
  "Multi-label OCR",
  "Private by design",
  "Scan memory",
  "Checked against your exact list",
  "Sodium, sugar, gluten and more",
  "Reads dense, small-print panels",
  "Your profile stays protected",
  "Revisit what you've already checked",
  "Vision AI reads the printed ingredients panel exactly as it's written.",
  "Every ingredient is checked against your saved allergens and conditions.",
  "Safe, caution, or do-not-eat — paired with the specific ingredient responsible.",
  "Set your profile",
  "Add your allergies, medical conditions, or things you're just avoiding. Takes under a minute.",
  "Scan any label",
  "Fill the frame with the ingredients panel. No barcode needed — just the printed text on the pack.",
  "Get a plain verdict",
  "Safe, caution, or do-not-eat — with the exact ingredient responsible.",
  "Chips & crisps",
  "Cookies & biscuits",
  "Bakery & pastries",
  "Dairy & yoghurt",
  "Drinks & coffee",
  "Candy & sweets",
,
  "Checking your account…",
  "Toggle menu",
  "Scroll to learn more",
  "Play video",
  "Seek — drag, click, or use arrow keys to jump to any point in the video",
  "Playback speed",
  "Scroll left",
  "Scroll right",
  "Languages supported",
  "When in doubt, don't eat it.",
  "Three steps between you and a safe snack",
  "One profile.",
  "Your allergies and conditions are saved to your account and checked automatically on every scan."
,
  "What a verdict actually looks like",
  "Choco wafer bar flagged for hidden peanut oil",
  "Listed as \"groundnut oil\" — a peanut derivative most labels don't spell out.",
  "Instant noodles came back at 42% daily sodium",
  "Within range for most people — flagged for anyone managing hypertension.",
  "Rice crackers cleared with no listed allergens",
  "Matched cleanly against a peanut and gluten profile in about 15–30 seconds.",
  "Danger",
  "Caution",
  "Snacks we catch",
  "every day",
  "A rotating look at the everyday packaged foods people scan most.",
  "Peanut butter granola",
  "Salted potato chips",
  "Sesame breadsticks",
  "Flavoured yoghurt cup",
  "Bottled cold brew",
  "Gummy fruit candy",
  "Try your own scan",
] as const;
