import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  Check,
  ChevronDown,
  Copy,
  Pill,
  Printer,
  ShieldAlert,
  Soup,
} from "lucide-react";
import {
  ALLERGY_SEVERITIES,
  GLUTEN_STATUSES,
  HYPERTENSION_STATUSES,
  KIDNEY_STATUSES,
  loadProfileStore,
  setActiveProfile,
  type StoredProfile,
} from "@/lib/profile";
import { Button } from "@/components/ui/button";
import { BottomNav } from "@/components/bottom-nav";
import { RequireEntry } from "@/components/require-entry";

export const Route = createFileRoute("/card")({
  head: () => ({
    meta: [
      { title: "PlateGuard AI — Emergency Card" },
      {
        name: "description",
        content:
          "A printable, shareable card listing allergies, conditions, and medications — for restaurants, schools, caregivers, or an ER visit.",
      },
    ],
  }),
  component: CardPage,
});

function labelFor(list: { value: string; label: string }[], value: string): string {
  return list.find((i) => i.value === value)?.label ?? value;
}

function CardPage() {
  return (
    <RequireEntry>
      <CardPageContent />
    </RequireEntry>
  );
}

function CardPageContent() {
  const [profiles, setProfiles] = useState<StoredProfile[]>([]);
  const [activeId, setActiveId] = useState("");
  const [switcherOpen, setSwitcherOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const store = loadProfileStore();
    setProfiles(store.profiles);
    setActiveId(store.activeId);
  }, []);

  const active = profiles.find((p) => p.id === activeId) ?? null;

  function switchTo(id: string) {
    setActiveProfile(id);
    setActiveId(id);
    setSwitcherOpen(false);
  }

  function cardText(p: StoredProfile): string {
    const lines = [`EMERGENCY HEALTH CARD — ${p.name || "Unnamed profile"}`, ""];
    if (p.allergens.length) {
      lines.push(
        `ALLERGIES (${p.allergySeverity ? labelFor(ALLERGY_SEVERITIES, p.allergySeverity) : "severity not set"}):`,
        p.allergens.join(", "),
        "",
      );
    }
    if (p.glutenStatus) {
      lines.push(`GLUTEN: ${labelFor(GLUTEN_STATUSES, p.glutenStatus)}`, "");
    }
    if (p.conditions.length) {
      lines.push("CONDITIONS:", p.conditions.join(", "), "");
    }
    if (p.hypertension.status) {
      lines.push(`CARDIOVASCULAR: ${labelFor(HYPERTENSION_STATUSES, p.hypertension.status)}`, "");
    }
    if (p.kidney.status) {
      lines.push(`KIDNEY: ${labelFor(KIDNEY_STATUSES, p.kidney.status)}`, "");
    }
    if (p.medications.trim()) {
      lines.push("CURRENT MEDICATIONS:", p.medications.trim(), "");
    }
    if (p.dietaryPatterns.length) {
      lines.push("DIETARY / RELIGIOUS PATTERN:", p.dietaryPatterns.join(", "), "");
    }
    if (p.notes.trim()) {
      lines.push("NOTES:", p.notes.trim(), "");
    }
    lines.push("Generated by PlateGuard AI — not a substitute for medical advice.");
    return lines.join("\n");
  }

  async function copyCard() {
    if (!active) return;
    try {
      await navigator.clipboard.writeText(cardText(active));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("[card] clipboard write failed:", err);
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <main className="mx-auto flex min-h-screen w-full max-w-md flex-col px-5 pb-24 pt-6 print:px-0 print:pb-0 print:pt-0">
        <header className="flex items-center gap-2 print:hidden">
          <Button asChild variant="ghost" size="icon" className="rounded-full">
            <Link to="/home">
              <ArrowLeft className="size-4" />
            </Link>
          </Button>
          <div>
            <h1 className="text-xl font-bold text-foreground">Emergency Card</h1>
            <p className="text-xs text-muted-foreground">
              Hand it to a server, a school nurse, or pull it up in an ER
            </p>
          </div>
        </header>

        {profiles.length > 1 && (
          <div className="relative mt-4 print:hidden">
            <button
              type="button"
              onClick={() => setSwitcherOpen((v) => !v)}
              className={`flex w-full items-center justify-between gap-2 border border-border bg-card/80 px-3.5 py-2.5 backdrop-blur transition-colors hover:bg-card ${
                switcherOpen ? "rounded-t-2xl border-b-0" : "rounded-2xl"
              }`}
            >
              <span className="text-sm font-medium text-foreground">
                {active?.name || "Select a profile"}
              </span>
              <ChevronDown
                className={`size-4 text-muted-foreground transition-transform ${switcherOpen ? "rotate-180" : ""}`}
              />
            </button>
            {switcherOpen && (
              <div className="overflow-hidden rounded-b-2xl border border-t-0 border-border bg-card shadow-xl">
                {profiles.map((p) => (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => switchTo(p.id)}
                    className="flex w-full items-center justify-between gap-2 border-t border-border/60 px-3.5 py-2.5 text-left text-sm transition-colors hover:bg-accent"
                  >
                    <span className="text-foreground">{p.name}</span>
                    {p.id === activeId && <Check className="size-4 text-primary" />}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}

        {!active ? (
          <div className="mt-16 flex flex-col items-center gap-3 text-center">
            <div className="flex size-16 items-center justify-center rounded-full bg-primary/12 text-primary">
              <ShieldAlert className="size-7" />
            </div>
            <p className="text-sm font-medium text-foreground">No profile yet</p>
            <p className="max-w-xs text-sm text-muted-foreground">
              Set up a profile first — the card is generated straight from it.
            </p>
            <Button asChild className="mt-2">
              <Link to="/profile">Create a profile</Link>
            </Button>
          </div>
        ) : (
          <>
            {/* The actual card — this is what print/share is built around */}
            <div className="mt-5 overflow-hidden rounded-3xl border-2 border-danger/30 bg-card shadow-lg print:mt-0 print:rounded-none print:border-black print:shadow-none">
              <div className="flex items-center gap-2 bg-danger px-5 py-3 text-danger-foreground print:bg-white print:text-black">
                <ShieldAlert className="size-5" />
                <p className="text-sm font-bold uppercase tracking-wide">Emergency Health Card</p>
              </div>

              <div className="space-y-4 p-5">
                <div>
                  <p className="text-xs uppercase tracking-widest text-muted-foreground">Name</p>
                  <p className="text-lg font-bold text-foreground">
                    {active.name || "Unnamed profile"}
                  </p>
                </div>

                {active.allergens.length > 0 && (
                  <div>
                    <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-widest text-danger">
                      <AlertTriangle className="size-3.5" />
                      Allergies
                      {active.allergySeverity && (
                        <span className="normal-case text-muted-foreground">
                          · {labelFor(ALLERGY_SEVERITIES, active.allergySeverity)}
                        </span>
                      )}
                    </p>
                    <p className="mt-1 text-base font-bold leading-snug text-danger">
                      {active.allergens.join(", ")}
                    </p>
                  </div>
                )}

                {active.glutenStatus && (
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                      Gluten
                    </p>
                    <p className="mt-1 text-sm font-medium text-foreground">
                      {labelFor(GLUTEN_STATUSES, active.glutenStatus)}
                    </p>
                  </div>
                )}

                {active.conditions.length > 0 && (
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                      Conditions
                    </p>
                    <p className="mt-1 text-sm font-medium text-foreground">
                      {active.conditions.join(", ")}
                    </p>
                  </div>
                )}

                {(active.hypertension.status || active.kidney.status) && (
                  <div className="grid grid-cols-2 gap-3">
                    {active.hypertension.status && (
                      <div>
                        <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                          Cardiovascular
                        </p>
                        <p className="mt-1 text-sm font-medium text-foreground">
                          {labelFor(HYPERTENSION_STATUSES, active.hypertension.status)}
                        </p>
                      </div>
                    )}
                    {active.kidney.status && (
                      <div>
                        <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                          Kidney
                        </p>
                        <p className="mt-1 text-sm font-medium text-foreground">
                          {labelFor(KIDNEY_STATUSES, active.kidney.status)}
                        </p>
                      </div>
                    )}
                  </div>
                )}

                {active.medications.trim() && (
                  <div>
                    <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                      <Pill className="size-3.5" />
                      Current medications
                    </p>
                    <p className="mt-1 text-sm font-medium text-foreground">{active.medications}</p>
                  </div>
                )}

                {active.dietaryPatterns.length > 0 && (
                  <div>
                    <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                      <Soup className="size-3.5" />
                      Dietary / religious pattern
                    </p>
                    <p className="mt-1 text-sm font-medium text-foreground">
                      {active.dietaryPatterns.join(", ")}
                    </p>
                  </div>
                )}

                {active.notes.trim() && (
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
                      Notes
                    </p>
                    <p className="mt-1 text-sm text-foreground">{active.notes}</p>
                  </div>
                )}

                {active.allergens.length === 0 &&
                  active.conditions.length === 0 &&
                  !active.medications.trim() && (
                    <p className="text-sm text-muted-foreground">
                      No allergies, conditions, or medications set yet for this profile.
                    </p>
                  )}

                <p className="border-t border-border pt-3 text-[11px] text-muted-foreground">
                  Generated by PlateGuard AI · not a substitute for medical advice
                </p>
              </div>
            </div>

            <div className="mt-4 flex gap-2 print:hidden">
              <Button className="h-12 flex-1 rounded-2xl" onClick={() => window.print()}>
                <Printer className="size-4" />
                Print
              </Button>
              <Button
                variant="secondary"
                className="h-12 flex-1 rounded-2xl"
                onClick={() => void copyCard()}
              >
                {copied ? <Check className="size-4" /> : <Copy className="size-4" />}
                {copied ? "Copied" : "Copy as text"}
              </Button>
            </div>
            <p className="mt-2 text-center text-xs text-muted-foreground print:hidden">
              "Copy as text" is the fastest way to paste this into a message to a caregiver, school,
              or restaurant staff.
            </p>
          </>
        )}
      </main>
      <div className="print:hidden">
        <BottomNav />
      </div>
    </div>
  );
}
